name: "Фреймворк для 2D MMO"
code_type: "php"
description: |-
    Набор вспомогательных библиотек для игр. На нем работает демонстрационная онлайн игра Игорь с открытым бесшовным миром. Git https://github.com/webrobot1/framework-rpg2d
init: |-
tick: |-		